name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  workflow_dispatch: # Permite execução manual do workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clona o repositório
        uses: actions/checkout@v2

      - name: Gera a animação da cobrinha
        uses: Platane/snk@v2
        with:
          github_user_name: rayenealmeida # Substitua pelo seu nome de usuário

      - name: Faz upload do resultado
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
